config/routes.rb
Rails.application.routes.draw do

  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
 root to: 'tests#index'

 devise_for :users,:tests, path: :gurus, path_names: { sign_in: :login, sign_out: :logout}

 scope "(:locale)", locale: /en|ru/ do
   resources :tests
 end

 get '/change_locale/:lang', to: 'settings#change_locale', as: :change_locale

 get :my_tests, to: 'test_passages#index'

 resources :user_badges, only: :index  do
   member do
     get :check
   end
 end

  resources :tests, only: :index  do
    member do
      post :start
    end
  end

  resources :badges, only: :index

  resources :test_passages, only: %i[show update] do

    member do
      get :result
    end
    resources :gists, only: %i[create index]
  end

  namespace :admin do
    resources :tests do
      patch :update_inline, on: :member
      post :ready, on: :member
      resources :questions, shallow: true, expect: :index do
        resources :answers, shallow: true, expect: :index
      end
    end
    resources :gists, only: %i[index]
    resources :users
    resources :badges
    resources :categories
  end

end

app/models/question.rb
class Question < ApplicationRecord
  has_many :answers, dependent: :destroy
  has_many :current_question, class_name: :TestPassage, foreign_key: :current_question_id
  has_many :gists, dependent: :destroy
  belongs_to :test

  validates :body, presence:true
  


end

app/models/test_passage.rb
class TestPassage < ApplicationRecord
  belongs_to :user
  belongs_to :test

  belongs_to :current_question, class_name: :Question, optional: true
  before_validation :before_validation_set_question, on: [:create, :update]
  TEST_SCORE_LIMIT = 0.85  #parameter for success score result


  def completed?
    current_question.nil?
  end

  def accept!(answer_ids)
    if correct_answer?(answer_ids)
      self.correct_question +=1
    end
    save!
  end

  def current_question_position
    self.test.questions.order(id: :desc).where('id < ?',self.current_question_id).count+1
  end

  def current_progress
    if self.completed?
      100
    else
      (current_question_position.to_f / test.questions.count) * 100.round(1)
    end
  end

  def test_result_check
    if self.test_result > TEST_SCORE_LIMIT
      true
    else
      false
    end
  end

  def test_result
    self.correct_question.to_f / self.test.questions.count.to_f.round(2)
  end


  def time_out?
    false unless self.time_left
  end

  def time_left
    self.test.timer - (Time.now - self.created_at).to_i if self.test.timer > 0
  end


  private

  def before_validation_set_question
    if self.current_question.present?
      self.current_question = next_question
    else
      set_first_question
    end
  end

  def set_first_question
    self.current_question = test.questions.first if test.present?

  end

  def correct_answer?(answer_ids)
    correct_answers_count = correct_answers.count
    correct_answers_count == correct_answers.where(id: answer_ids).count &&
    correct_answers_count == answer_ids.count
  end

  def correct_answers
    current_question.answers.correct
  end

  def next_question
    test.questions.order(:id).where('id > ?', current_question.id).first

  end

end

app/controllers/test_passages_controller.rb
class TestPassagesController < ApplicationController
  skip_before_action :verify_authenticity_token, only: %i[update]
  before_action :set_test_pessage, only: %i[show update result gist]

  def index
  end

  def show
  end

  def result

  end

  def update
    @test_passage.accept!(params[:answer_ids])
    if @test_passage.completed? || @test_passage.time_out?
      # все проверки запускаются только в случае, если тест выполнен успешно
      if @test_passage.test_result_check
        badges_count = current_user.badges.size
        CheckAchivementsService.new(@test_passage, current_user).call
        flash[:notice] = t('got_achivement') if current_user.badges.size > badges_count
      end
      TestsMailer.completed_test(@test_passage).deliver_now
      redirect_to result_test_passage_path(@test_passage)
    else
      render :show
    end
  end


  private

  def set_test_pessage
    @test_passage = TestPassage.find(params[:id])

  end



end

app/helpers/test_passages_helper.rb
module TestPassagesHelper

  def show_result(test_passage)
    html = ""
    if test_passage.test_result_check
      html << t('.header.passed', title: @test_passage.test.title)
      html << "<h3 style='color: green;' >"
      html << t('helpers.score.passed')
      html << "#{test_passage.test_result*100}%</h3>"
      html.html_safe
    else
      html << t('.header.failed', title: @test_passage.test.title)
      html << "<h3 style='color: red;' >"
      html << t('helpers.score.failed')
      html << "#{test_passage.test_result*100}%</h3>"
      html.html_safe
    end
  end

end

app/views/test_passages/index.html.erb
<div class="container">
  <h2><%= t('.header')%></h2>

  <table class="table">
    <% if current_user.test_passages.present?%>
    <thead>
      <tr>
        <th scope="col"><%= t('.id')%></th>
        <th scope="col"><%= t('.test_title')%></th>
        <th scope="col"><%=t('.started')%></th>
        <th scope="col"><%= t('.progress')%></th>
        <th scope="col"><%=t('.action')%></th>

      </tr>
    </thead>
    <tbody>
      <% current_user.test_passages.order(created_at: :desc).each do |tp| %>

      <tr>
        <td><%= tp.id %></td>
        <td><%= tp.test.title %></td>
        <td><%= tp.created_at %></td>
        <th>

          <div class="progress">
              <div class="progress-bar progress-bar-striped progress-bar-animated"
                   role="progressbar"
                   id = "progress-bar"
                   aria-valuenow="75"
                   aria-valuemin="0"
                   aria-valuemax="100"
                   style="width: <%  tp.current_progress%>%"
                   data-progress="<%= tp.current_progress %>">
                   <%= tp.current_progress.ceil %>
              </div>
            </div>
        </th>
        <td>
          <% unless tp.completed? %>
            <%= link_to t('continue'), test_passage_path(tp), class: "btn btn-light" %></td>
          <% end %>
      </tr>
      <% end %>
    <% else %>
      <p> <%= t('.not_started')%> </p>

    <% end %>
    </tbody>
  </table>
</div>

app/views/test_passages/result.html.erb
<div class="container" >
  <div class="row">

      <h4 ><%= show_result(@test_passage) %></h4>
      <p></p>


    <div class="container" style = "border:none">
      <p>
        <%= link_to t('nav.back.tests'), tests_path, class: "btn btn-primary" %>
      </p>

    </div>
  </div>
</div>

app/views/test_passages/show.html.erb
<div class="container">


  <%= content_tag :div,
                "#{ t('timer') }",
                class: 'timer',
                data: { timer: @test_passage.time_left } %>

  <div class="card mx-auto" style = "border:none">
    <h1><%= t('.header', title: @test_passage.test.title) %> </h1>
    <p>
      <h3><%= t('.question_header',
           current:@test_passage.current_question_position,
           total: @test_passage.test.questions.count )%>
      </h3>


    <div class="progress">
      <div class="progress-bar progress-bar-striped progress-bar-animated"
           role="progressbar"
           id = "progress-bar"
           aria-valuenow="75"
           aria-valuemin="0"
           aria-valuemax="100"
           style="width: <%  @test_passage.current_progress%>%"
           data-progress="<%= @test_passage.current_progress %>">

      </div>
    </div>
  </div>

  <div class="card  mx-auto" style = "border:none">
    <%= @test_passage.current_question.body%>
    <div class="card-body" style = "border:none">
      <%= form_with url: test_passage_path(@test_passage),
                         local:true,
                         data: {turbo: false},
                         method: :put do |form| %>

        <%= form.collection_check_boxes :answer_ids,
                          @test_passage.current_question.answers,
                          :id,
                          :title,
                          include_hidden: false do |b| %>
        <p>
          <%= b.check_box id: "answer_ids_#{b.object.id}"%>
          <%= b.label%>
        </p>
        <% end%>

        <p>
          <%= form.submit 'Next' %>
        </p>
      <% end %>
      <p>
        <%= link_to t('gist_question'), test_passage_gists_path(@test_passage),
                                        data:{turbo_method: "post"},
                                        class: "btn btn-warning bi bi-chat-left-heart" %>
      </p>
    </div>

  </div>
</div>