config/routes.rb
Rails.application.routes.draw do

  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
 root to: 'tests#index'

 devise_for :users,:tests, path: :gurus, path_names: { sign_in: :login, sign_out: :logout}

 scope "(:locale)", locale: /en|ru/ do
   resources :tests
 end

 get '/change_locale/:lang', to: 'settings#change_locale', as: :change_locale

 get :my_tests, to: 'test_passages#index'

 resources :user_badges, only: :index  do
   member do
     get :check
   end
 end

  resources :tests, only: :index  do
    member do
      post :start
    end
  end

  resources :badges, only: :index

  resources :test_passages, only: %i[show update] do

    member do
      get :result
    end
    resources :gists, only: %i[create index]
  end

  namespace :admin do
    resources :tests do
      patch :update_inline, on: :member
      post :ready, on: :member
      resources :questions, shallow: true, expect: :index do
        resources :answers, shallow: true, expect: :index
      end
    end
    resources :gists, only: %i[index]
    resources :users
    resources :badges
    resources :categories
  end

end

app/views/shared/_footer.html.erb
<footer>
  <div class="row align-items-end">
    <div class="col-md-auto">
      <%= Time.zone.now %>
    </div>
    <div class="col">
      <%= t('author')%>
    </div>
    <div class="col">
      <%=  Rails.configuration.author_app %>
    </div>
    <div class="col">
      <%= github_url %>
    </div>
    <div class="col-md-auto">
      <%= link_to t('school'), "http://thinknetica.com/", :target => "_blank" %>
    </div>
    <div class="col-md-auto">
      <%=t('year')%>
    </div>
    <div class="col">
      <%= footer_year_data %>
    </div>
  </div>


</footer>

app/views/shared/_nav.html.erb
<nav class="navbar navbar-light bg-light">
  <div class=".container-fluid">
    <div class="navbar-brand menu-hover">
      <%= link_to t('TestGuru'), tests_path, class: 'navbar-brand bi bi-boxes' %>
    </div>
    </div>
    <div class="nav-link hover" >
      <% if user_signed_in? %>
      <% if current_user.admin? %>
          <%= link_to '', admin_tests_path, class: 'bi bi-wrench-adjustable' %>
        <% else %>
    </div>


    <div class="nav-link hover">
      <%= link_to t('nav.menu.all_tests'), tests_path %>
    </div>

    <div class="nav-link hover">
        <%= link_to t('nav.menu.my_tests'), my_tests_path %>
    </div>

    <div class="nav-link hover">
        <%= link_to t('nav.menu.my_badges'), user_badges_path %>
    </div>


    <div class="nav-link hover">
        <%= link_to t('nav.menu.profile'), edit_user_registration_path %>
    </div>

    <div class="nav-link hover">
        <%= link_to t('nav.menu.back'), :back %>
    </div>
    <div class="menu">

        <%= t('welcome', title: current_user.first_name)%> <b> <%= current_user.email %> </b>
    </div>
    <div class="col-md-auto">
        <%= link_to "Eng", change_locale_path(:en) %> |
        <%= link_to "Rus", change_locale_path(:ru)%>
    </div>

    <div class="col-md-auto">
        <%= link_to t('nav.menu.quit'), destroy_user_session_path,
                                          data: { turbo_method: "delete"},
                                          class: "btn btn-primary bi bi-box-arrow-right" %>
        <% end %>
    </div>
      <% else %>
        <%= link_to t('login'), new_session_path(resource_name) %>
        <%= link_to t('signup'), new_registration_path(resource_name) %>

      <% end %>


</nav>