config/routes.rb
Rails.application.routes.draw do

  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
 root to: 'tests#index'

 devise_for :users,:tests, path: :gurus, path_names: { sign_in: :login, sign_out: :logout}

 scope "(:locale)", locale: /en|ru/ do
   resources :tests
 end

 get '/change_locale/:lang', to: 'settings#change_locale', as: :change_locale

 get :my_tests, to: 'test_passages#index'

 resources :user_badges, only: :index  do
   member do
     get :check
   end
 end

  resources :tests, only: :index  do
    member do
      post :start
    end
  end

  resources :badges, only: :index

  resources :test_passages, only: %i[show update] do

    member do
      get :result
    end
    resources :gists, only: %i[create index]
  end

  namespace :admin do
    resources :tests do
      patch :update_inline, on: :member
      post :ready, on: :member
      resources :questions, shallow: true, expect: :index do
        resources :answers, shallow: true, expect: :index
      end
    end
    resources :gists, only: %i[index]
    resources :users
    resources :badges
    resources :categories
  end

end

app/models/answer.rb
class Answer < ApplicationRecord
  belongs_to :question
  validates :title, presence:true
  validate :answers_count_check?, on: [:create, :update]

  scope :correct, ->{where(correct:true)}

  private
  def answers_count_check?
    errors.add(:title) if question.answers.count > 4
  end
end

app/controllers/admin/answers_controller.rb
class Admin::AnswersController < Admin::BaseController
  before_action :find_question, only: %i[ new create ]
  before_action :set_answer, only: %i[ show edit update destroy ]


  def show

  end

  def new
    @answer = @question.answers.new
  end

  def edit

  end

  def create
    @answer = @question.answers.new(answer_params)
    if @answer.save
      redirect_to admin_question_path(@answer.question)
    else
      render :new, status: :unprocessable_entity
    end
  end


  def update
    if @answer.update(answer_params)
      redirect_to admin_question_path(@answer.question)
    else
        render :edit, status: :unprocessable_entity
    end

  end

  def destroy
    @answer.destroy
    redirect_to admin_question_path(@answer.question), status:303
  end

  private

    def find_question
      @question = Question.find(params[:question_id])
    end

    def set_answer
      @answer = Answer.find(params[:id])
    end

    def answer_params
      params.require(:answer).permit(:title,:correct)
    end
end

app/helpers/answers_helper.rb
module AnswersHelper
end

app/views/admin/answers/_answer.html.erb
<li class="list-group-item">
  <div class="row align-items-start">
    <div class="col col-md">
      <%= answer.title%>
    </div>
    <div class="col-md-auto">
      <%= link_to t('edit'), edit_admin_answer_path(answer), class: "btn btn-warning"%>

    </div>
    <div class="col-md-auto">
      <%= button_to t('delete'), admin_answer_path(answer),
                                         method: :delete, class: "btn btn-danger bi bi-eraser",
                                         form: {
                                           data: { confirm: t('confirm')}
                                         }%>
    </div>
  </div>
</li>

app/views/admin/answers/_form.html.erb
<%= form_with model: [:admin,@question, @answer], data:{turbo:true} do |form| %>
  <%= render 'admin/shared/errors', resource: @answer %>

  <div class="card border-0 w-50 align-items-center"">
    <div class="card-body">

    <%= form.label :title%>
    <%= form.text_area :title, id: :answer_body,  rows:7, cols: 60%>

    <%= form.label :correct%>
    <%= form.check_box :correct, id: :answer_correct%>

    </div>
</div>

  <div>
    <%= form.submit t('submit'), class: "btn btn-primary"%>
  </div>
<% end %>

app/views/admin/answers/edit.html.erb
<%= render 'admin/shared/errors', resource: @answer %>
<h1><%= t('.edit')%></h1>

<%= render 'form' %>

<br>
<p></p>
<div>

  <p></p>
  <%= link_to t('nav.back.answers'), admin_question_path(@answer.question) %>
</div>

app/views/admin/answers/new.html.erb
<h3><%= t('.create')%></h3>
<div class="container md-auto">
  <%= render 'form' %>
  <%= link_to t('nav.back.answers'), admin_question_path(@question), class: "btn btn-info" %>
</div>